name: RISD
highlighter: pygments
safe: true
markdown: kramdown
exclude:
  - "Gemfil*"
  - "Procfil*"
  - "*.command"
  - README.md
  - "assets/style/scss/*"
  - "assets/js/src/*"
baseurl: /new-years-2016
